# Tree Generation Parameters
species: [50]
birth_death_rates:
  - [1.0, 2.0]
seeds: [1]

sampling_fraction: [0.25]
mutation_rate: [1.0]

evolver_path: "/Users/mrzi/Documents/software/paml4/paml/src/evolver"

# TKF92 Simulation Parameters
tkf_lambda: 0.1
tkf_mu: 0.11
tkf_r: 0.8
max_insertion_length: 50
simulate_tkf_path: "/Users/mrzi/Documents/develop/simulate_tkf/target/debug/simulate_tkf"

# JATI Tree Inference Parameters
jati_path: "/Users/mrzi/Documents/develop/jati_tkf/JATI/target/debug/jati"
jati_models: ["jc69"]
jati_paras: [0.3, 0.4, 0.5]
gap_handling_strategies: ["PIP", "TKF92"]
max_iterations: 1

# Paths
python_bin: "/Users/mrzi/miniforge3/envs/snakemake/bin/python3"
sim_dir: "results/msas/s{s}_b{b}_d{d}_f{f}_m{m}_seed{seed}"
inf_dir: "results/inference/s{s}_b{b}_d{d}_f{f}_m{m}_seed{seed}/{model}_{gap}_jati"

# Regex for parsing paths in aggregate_results.py
# Use named groups (?P<name>...) to define the fields to extract
sim_match: 's(?P<species>\d+)_b(?P<birth_rate>[\d.]+)_d(?P<death_rate>[\d.]+)_f(?P<sampling_fraction>[\d.]+)_m(?P<mutation_rate>[\d.]+)_seed(?P<seed>\d+)'
inf_match: '(?P<jati_model>[^/]+)_(?P<gap_strategy>[^/]+)_jati'
