# NOTE on Regex Fields:
# 'tree_match', 'match_regex', and 'inf_match' are used by scripts/aggregate_results.py
# to extract metadata (like species count, mutation rates, etc.) directly from 
# the directory names of the inference outputs into the final summary TSV.

# General
seeds: [1]
python_bin: "/Users/mrzi/miniforge3/envs/snakemake/bin/python3"

# PAML Tree Generation Parameters
evolver_path: "/Users/mrzi/Documents/software/paml4/paml/src/evolver"
# species: [128, 64, 32, 16]
species: [8, 16, 32, 64]
birth_death_rates:
  - [1.0, 2.0]
sampling_fraction: [0.25]
mutation_rate: [1.0]
tree_params_path_snippet: "s{s}_b{b}_d{d}_f{f}_m{m}_seed{seed}"
tree_path: "results/trees/{tree_params_path_snippet}.nwk"
tree_match: 's(?P<species>\d+)_b(?P<birth_rate>[\d.]+)_d(?P<death_rate>[\d.]+)_f(?P<sampling_fraction>[\d.]+)_m(?P<mutation_rate>[\d.]+)_seed(?P<seed>\d+)'

# MSA Simulation Tools & Their Parameters
msa_dir_path: "results/msas/{tree_params_path_snippet}/{msa_sim_tool}/{tool_params}"
msa_sim_tools:
  tkf:
    binary_path: "/Users/mrzi/Documents/develop/simulate_tkf/target/debug/simulate_tkf"
    lambda: 0.03
    mu: 0.0303
    r: 0.8
    max_ins: 50
    root_lengths: [500] # we choose params above to get expected 500 length at the root
    params_path_snipped: "l{lambda}_mu{mu}_r{r}_max{max_ins}_len{root_length}"
    match_regex: 'tkf/l(?P<tkf_lambda>[\d.]+)_mu(?P<tkf_mu>[\d.]+)_r(?P<tkf_r>[\d.]+)_max(?P<max_ins>\d+)_len(?P<root_length>\d+)'
  
  alisim:
    binary_path: "/Users/mrzi/Documents/software/iqtree3/iqtree3/build/iqtree3"
    model: "JC"
    root_lengths: [500]
    indel_params: # (insertion_rate, deletion_rate)
    # For simulations with indels, we applied empirical parameters (Graur et al. 1989; Gu and Li 1995; Cartwright 2009) with the insertion and deletion rates of 0.03 and 0.09, respectively, and the indel-lengths drawn from a truncated Zipfian (Power-Law) distribution (Fletcher and Yang 2009) (a = 1.7; max = 100). alisim paper and these seem to be also the default params for alisim
      - [0.006, 0.018]
    params_path_snipped: "ir{ir}_ip{ip}_len{root_length}"
    match_regex: 'alisim/ir(?P<ir>[\d.]+)_ip(?P<ip>[\d.]+)_len(?P<root_length>\d+)'

# Inference Tools & Their Parameters
inference_tools:
  jati:
    binary_path: "/Users/mrzi/Documents/develop/jati_tkf/JATI/target/debug/jati"
    models: ["jc69"]
    params: [0.3, 0.4, 0.5]
    gap_strategies: ["PIP", "TKF92"]
    max_iterations: 5
    path_snippet: "{model}_{gap}"
    match_regex: 'jati/(?P<model>[^/]+)_(?P<gap_strategy>[^/]+)'
  iqtree:
    binary_path: "/Users/mrzi/Documents/software/iqtree3/iqtree3/build/iqtree3"
    models: ["JC"]
    path_snippet: "{model}"
    match_regex: 'iqtree/(?P<model>[^/]+)'

inf_dir_path: "results/inference/{tree_params_path_snippet}/{msa_sim_tool}/{tool_params}/{inference_tool}/{inf_params}"

